### ISSUE TITLE
Build status widget

### ISSUE THREAD

**Issue by bbss** [Wiredcraft/dashy#110]
We want dashy to display when a build for a configurable project has passed or failed. 

The configuration for the widget wil look like this: 

``` yaml
 - build-widget-id:
     attributes:
       Octokan: 
         datasource-id-of-worker: octokan
       Octochat: 
         datasource-id-of-worker: octochat
     type: BuildStatus
```

Which would mean the following yaml config for the dashyserver

sources/datasource-id-of-worker.yaml

``` yaml
name: Build status datasources
webhooks:
        - build-status-webhook
```

So the worker can start pushing build status updates to the build-status-webhook with the following json format:

``` json
{
  time : utctime,
  data: {
     build : build-id
     success: bool
   }
}
```

Where build-id could be the git commit ref if we decide to include the git commit message in the widgets. We could later change success to be status and choose from 'building', 'success' and 'failure'.
